# Generated by Django 6.0.5 on 2026-08-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driver_approval_status_driver_license_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='license_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_color',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
