# Generated by Django 6.0.5 on 2026-08-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_driver_license_number_driver_vehicle_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='region',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
