# Generated by Django 6.0.5 on 2026-08-01 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farezones', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FareRate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_per_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('effective_from', models.DateTimeField(auto_now_add=True)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rates', to='vehicles.vehicletype')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rates', to='farezones.farezone')),
            ],
            options={
                'indexes': [models.Index(condition=models.Q(('effective_to__isnull', True)), fields=['zone', 'vehicle_type'], name='one_active_rate_zone_vehicle')],
            },
        ),
    ]
