# Generated by Django 6.0.5 on 2026-08-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='DriverCommissionBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_distance_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_distance_km', models.DecimalField(blank=True, decimal_places=2, help_text="Leave empty to mean 'above min_distance_km'.", max_digits=8, null=True)),
                ('commission_percent', models.DecimalField(decimal_places=2, help_text='Percentage of the pickup fare paid to the driver.', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['min_distance_km', 'max_distance_km'],
            },
        ),
    ]