# Generated by Django 6.0.5 on 2026-08-01 22:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('farerates', '0001_initial'),
        ('orders', '0001_initial'),
        ('stations', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoTrip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leg_type', models.CharField(choices=[('pickup', 'Pickup'), ('station_transfer', 'Station Transfer'), ('final_delivery', 'Final Delivery')], default='pickup', max_length=20)),
                ('pickup_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_address_text', models.TextField(blank=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fare_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('searching_driver', 'Searching Driver'), ('driver_assigned', 'Driver Assigned'), ('en_route_to_pickup', 'En Route To Pickup'), ('arrived_at_pickup', 'Arrived At Pickup'), ('picked_up', 'Picked Up'), ('delivered_to_station', 'Delivered To Station'), ('cancelled', 'Cancelled')], default='requested', max_length=25)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('driver_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at_pickup_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips_as_destination', to='stations.cargostation')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='drivers.driver')),
                ('fare_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='farerates.farerate')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='orders.cargoorder')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='vehicles.vehicletype')),
            ],
            options={
                'indexes': [models.Index(fields=['order'], name='idx_trips_order'), models.Index(fields=['driver'], name='idx_trips_driver'), models.Index(fields=['status'], name='idx_trips_status')],
            },
        ),
    ]
