# Generated by Django 6.0.5 on 2026-08-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargotrip',
            name='fare_rate',
        ),
        migrations.AlterField(
            model_name='cargotrip',
            name='destination_station',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cargotrip',
            name='pickup_address_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cargotrip',
            name='vehicle_type',
            field=models.IntegerField(default=1),
        ),
    ]
