# Generated by Django 6.0.5 on 2026-08-01 22:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargosizes', '0001_initial'),
        ('stations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estimated_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('pickup_in_progress', 'Pickup In Progress'), ('at_origin_station', 'At Origin Station'), ('cancelled', 'Cancelled')], default='pending', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cargo_size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='cargosizes.cargosize')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('destination_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_as_destination', to='stations.cargostation')),
                ('origin_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_as_origin', to='stations.cargostation')),
            ],
            options={
                'indexes': [models.Index(fields=['customer'], name='idx_orders_customer'), models.Index(fields=['status'], name='idx_orders_status')],
                'constraints': [models.CheckConstraint(condition=models.Q(('origin_station', models.F('destination_station')), _negated=True), name='origin_ne_destination')],
            },
        ),
    ]
