# Generated by Django 6.0.5 on 2026-08-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cargoorder',
            name='origin_ne_destination',
        ),
        migrations.AddField(
            model_name='cargoorder',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cargoorder',
            name='receiver_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cargoorder',
            name='receiver_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='cargoorder',
            name='receiver_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='cargoorder',
            name='cargo_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cargoorder',
            name='destination_station',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cargoorder',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cargoorder',
            name='origin_station',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cargoorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('pickup_in_progress', 'Pickup In Progress'), ('at_origin_station', 'At Origin Station'), ('cancelled', 'Cancelled')], default='submitted', max_length=25),
        ),
    ]
